# Static

- type: latheRecipePack
  id: SecurityPracticeStaticImp
  recipes:
  - MagazineBoxLPistolPractice
  - MagazineLPistolPractice

- type: latheRecipePack
  id: SecurityAmmoStaticImp
  recipes:
  - MagazineBoxLPistol
  - MagazineDMR
  - MagazineDMREmpty
  - MagazineLPistol
  - MagazineLPistolEmpty

# Dynamic

- type: latheRecipePack
  id: SecurityEquipmentImp
  recipes:
  - PRIbarPlusConversionKit

- type: latheRecipePack
  id: SecurityAmmoImp
  recipes:
  - MagazineBoxLPistolIncendiary
  - MagazineBoxLPistolUranium
  - MagazineDMRIncendiary
  - MagazineDMRUranium
  - MagazineLPistolIncendiary
  - MagazineLPistolUranium

- type: latheRecipePack
  id: SecurityWeaponsImp
  recipes:
  - FullAutoConversionKit
  - HyperBurstConversionKit

- type: latheRecipePack
  id: SecurityDisablersImp
  recipes:
  - WeaponShotgunEnforcerBeanbag
  - WeaponShotgunKammererBeanbag
