using Content.Shared._VDS.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._VDS.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class CustomizationTab : Control
{
    public CustomizationTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionOOCColorSlider(VCCVars.OOCColor, OOCColorSlider);
        OOCColorSlider.Slider.OnColorChanged += OnColorChanged;
        Control.Initialize();
    }

    private void OnColorChanged(Color color)
    {
        Control.ValueChanged();
    }
}
